name: Pylint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Pylint with badge support
      uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: |
          src
        python-version: 3.12
        requirements-path: requirements.txt
        readme-path: README.md        # This line enables automatic badge updates
        pylintrc-path: .pylintrc      # Optional, if you use one
        badge-text: PyLint
        color-bad-score: red
        color-ok-score: orange
        color-good-score: yellow
        color-perfect-score: brightgreen
